"""add remark to inventory

Revision ID: 59c2515616d9
Revises: 9a8497799ad4
Create Date: 2019-12-24 17:55:45.930063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59c2515616d9'
down_revision = '9a8497799ad4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory', sa.Column('remark', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory', 'remark')
    # ### end Alembic commands ###
