"""init

Revision ID: 9a8497799ad4
Revises: 
Create Date: 2019-12-23 16:27:11.746196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a8497799ad4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mat_code', sa.String(length=10), nullable=True),
    sa.Column('mat_name', sa.String(length=30), nullable=True),
    sa.Column('sto_code', sa.Integer(), nullable=True),
    sa.Column('sto_name', sa.String(length=30), nullable=True),
    sa.Column('acount', sa.String(length=10), nullable=True),
    sa.Column('lastdt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('allocation', sa.String(length=10), nullable=True),
    sa.Column('code', sa.String(length=10), nullable=True),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('inventory_acount', sa.Integer(), nullable=True),
    sa.Column('lastdt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('material',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('pcs', sa.String(length=1), nullable=True),
    sa.Column('state', sa.String(length=10), nullable=True),
    sa.Column('remark', sa.String(length=200), nullable=True),
    sa.Column('lastdt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('package',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('describe', sa.Enum('千克', '件', '托', '箱', '只', '支', '组', '卷', '立方米', '平方米'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('safety',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=True),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('acount', sa.String(length=10), nullable=True),
    sa.Column('remark', sa.String(length=200), nullable=True),
    sa.Column('lastdt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('describe', sa.Enum('停用', '启用'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('storage',
    sa.Column('allocation', sa.String(length=10), nullable=False),
    sa.Column('remark', sa.String(length=200), nullable=True),
    sa.Column('state', sa.String(length=10), nullable=True),
    sa.Column('lastdt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('allocation')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('storage')
    op.drop_table('state')
    op.drop_table('safety')
    op.drop_table('package')
    op.drop_table('material')
    op.drop_table('inventory')
    op.drop_table('history')
    # ### end Alembic commands ###
