"""material tab

Revision ID: fda6b65b2f76
Revises: 
Create Date: 2019-12-19 18:14:54.575258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fda6b65b2f76'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('material',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('pcs', sa.String(length=1), nullable=True),
    sa.Column('state', sa.String(length=1), nullable=True),
    sa.Column('remark', sa.String(length=200), nullable=True),
    sa.Column('lastdt', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('material')
    # ### end Alembic commands ###
